[project]
name = "Karuna"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.karuna]
path = "contracts/karuna.clar"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
